# Generated by Django 5.0.4 on 2024-04-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworkapp2', '0002_imag_alter_order_data_alter_order_summa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imag',
            name='images',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
